const SHUFFLED_GRE_WORDS = [
  { word: "Quiescent", definition: "Inactive or dormant." },
  { word: "Tirade", definition: "Long angry speech." },
  { word: "Abridge", definition: "To shorten a text without losing its essence." },
  { word: "Dichotomy", definition: "Division between opposing concepts." },
  { word: "Plastic", definition: "Able to be molded." },
  { word: "Tractable", definition: "Easy to control." },
  { word: "Perennial", definition: "Lasting for a long time." },
  { word: "Discordant", definition: "Lacking harmony; conflicting." },
  { word: "Aberrant", definition: "Deviating from the norm or standard." },
  { word: "Docile", definition: "Easily taught or managed." },
  { word: "Laconic", definition: "Using very few words." },
  { word: "Qualified", definition: "Limited or conditional." },
  { word: "Pragmatic", definition: "Practical and realistic." },
  { word: "Disabuse", definition: "To free from false belief." },
  { word: "Laudable", definition: "Deserving praise." },
  { word: "Stolid", definition: "Calm and showing little emotion." },
  { word: "Ambiguous", definition: "Open to more than one interpretation." },
  { word: "Recalcitrant", definition: "Stubbornly uncooperative." },
  { word: "Disparage", definition: "To belittle or disrespect." },
  { word: "Soporific", definition: "Tending to induce sleep." },
  { word: "Lethargic", definition: "Sluggish and apathetic." },
  { word: "Reverent", definition: "Showing deep respect." },
  { word: "Assuage", definition: "To make an unpleasant feeling less intense." },
  { word: "Sporadic", definition: "Occurring irregularly." },
  { word: "Pithy", definition: "Concise and full of meaning." },
  { word: "Extrapolate", definition: "To extend or project." },
  { word: "Sage", definition: "Wise person." },
  { word: "Disinterested", definition: "Impartial or unbiased." },
  { word: "Belie", definition: "To give a false impression." },
  { word: "Arcane", definition: "Known or understood by few; mysterious." },
  { word: "Zeal", definition: "Great energy for a cause." },
  { word: "Prosaic", definition: "Dull and lacking imagination." },
  { word: "Innocuous", definition: "Harmless or inoffensive." },
  { word: "Esoteric", definition: "Intended for a small group." },
  { word: "Anomaly", definition: "Something that deviates from the norm." },
  { word: "Penurious", definition: "Extremely poor; stingy." },
  { word: "Inundate", definition: "To overwhelm." },
  { word: "Disparate", definition: "Essentially different in kind." },
  { word: "Bombastic", definition: "Pompous in speech or writing." },
  { word: "Solicitous", definition: "Showing concern or care." },
  { word: "Garrulous", definition: "Excessively talkative." },
  { word: "Pungent", definition: "Strong and sharp in taste/smell." },
  { word: "Precipitate", definition: "To cause suddenly." },
  { word: "Avarice", definition: "Extreme greed for wealth." },
  { word: "Exigent", definition: "Urgent or requiring action." },
  { word: "Tacit", definition: "Understood without being stated." },
  { word: "Artless", definition: "Without guile; natural and sincere." },
  { word: "Exculpate", definition: "To clear from blame." },
  { word: "Ameliorate", definition: "To improve or make better." },
  { word: "Dirge", definition: "A mournful song or poem." },
  { word: "Deride", definition: "To mock or ridicule." },
  { word: "Alacrity", definition: "Cheerful readiness or eagerness." },
  { word: "Fledgling", definition: "New or inexperienced." },
  { word: "Cogent", definition: "Convincing and logical." },
  { word: "Mendacious", definition: "Untruthful." },
  { word: "Plethora", definition: "Excessive amount." },
  { word: "Diatribe", definition: "A bitter verbal attack." },
  { word: "Veracious", definition: "Truthful or honest." },
  { word: "Obtuse", definition: "Slow to understand." },
  { word: "Verbose", definition: "Using more words than needed." },
  { word: "Abscond", definition: "To leave hurriedly and secretly to avoid detection." },
  { word: "Alleviate", definition: "To make suffering less severe." },
  { word: "Discrepancy", definition: "Lack of consistency." },
  { word: "Diffident", definition: "Lacking self-confidence." },
  { word: "Capricious", definition: "Given to sudden changes." },
  { word: "Inchoate", definition: "Not fully formed." },
  { word: "Austere", definition: "Severely plain or simple in style." },
  { word: "Iconoclast", definition: "Attacker of cherished beliefs." },
  { word: "Inimical", definition: "Hostile or harmful." },
  { word: "Penchant", definition: "Strong liking for something." },
  { word: "Itinerant", definition: "Traveling from place to place." },
  { word: "Aplomb", definition: "Self-confidence in demanding situations." },
  { word: "Abstruse", definition: "Difficult to understand; obscure." },
  { word: "Attenuate", definition: "To reduce in force or intensity." },
  { word: "Equivocate", definition: "To use ambiguous language." },
  { word: "Impecunious", definition: "Having little money." },
  { word: "Philanthropic", definition: "Seeking to promote welfare." },
  { word: "Quibble", definition: "Minor objection or criticism." },
  { word: "Facilitate", definition: "To make easier." },
  { word: "Platitude", definition: "Overused unoriginal remark." },
  { word: "Mundane", definition: "Ordinary and lacking excitement." },
  { word: "Aesthetic", definition: "Relating to beauty or appreciation of beauty." },
  { word: "Magnanimous", definition: "Generous or forgiving." },
  { word: "Prodigal", definition: "Wastefully extravagant." },
  { word: "Venerate", definition: "To regard with respect." },
  { word: "Incisive", definition: "Sharp and clear in thinking." },
  { word: "Insular", definition: "Narrow-minded or isolated." },
  { word: "Adulation", definition: "Excessive praise or admiration." },
  { word: "Sanction", definition: "Official approval; penalty." },
  { word: "Satiate", definition: "To satisfy fully." },
  { word: "Effrontery", definition: "Shameless boldness." },
  { word: "Refute", definition: "To prove wrong." },
  { word: "Luminous", definition: "Bright or shining." },
  { word: "Eulogy", definition: "Speech praising someone." },
  { word: "Maverick", definition: "Independent-minded person." },
  { word: "Presumptuous", definition: "Overstepping boundaries." },
  { word: "Ebullient", definition: "Overflowing with enthusiasm." },
  { word: "Deleterious", definition: "Harmful or damaging." },
  { word: "Probity", definition: "Honesty and integrity." },
  { word: "Inadvertent", definition: "Unintentional." },
  { word: "Gainsay", definition: "To deny or contradict." },
  { word: "Stint", definition: "Period of work." },
  { word: "Reticent", definition: "Reserved or reluctant." },
  { word: "Propitiate", definition: "To appease or win favor." },
  { word: "Ephemeral", definition: "Lasting a very short time." },
  { word: "Ingenuous", definition: "Innocent and unsuspecting." },
  { word: "Implicit", definition: "Implied though not stated." },
  { word: "Cacophony", definition: "Harsh discordant sound." },
  { word: "Dither", definition: "To hesitate indecisively." },
  { word: "Misanthrope", definition: "Person who dislikes humankind." },
  { word: "Desiccate", definition: "To dry out completely." },
  { word: "Viscous", definition: "Thick and sticky consistency." },
  { word: "Intransigent", definition: "Unwilling to compromise." },
  { word: "Preclude", definition: "To prevent from happening." },
  { word: "Whimsical", definition: "Playfully quaint or fanciful." },
  { word: "Aver", definition: "To assert or affirm confidently." },
  { word: "Recondite", definition: "Little known; obscure." },
  { word: "Exacerbate", definition: "To make worse." },
  { word: "Perfidious", definition: "Deceitful and untrustworthy." },
  { word: "Pedantic", definition: "Overly concerned with rules." },
  { word: "Enumerate", definition: "To list one by one." },
  { word: "Efficacy", definition: "Ability to produce desired effect." },
  { word: "Enervate", definition: "To weaken or drain energy." },
  { word: "Preamble", definition: "Introductory statement." },
  { word: "Vacillate", definition: "To waver between opinions." },
  { word: "Spectrum", definition: "Range of different positions." },
  { word: "Grandiloquent", definition: "Pompous in speech." },
  { word: "Impassive", definition: "Not showing emotion." },
  { word: "Taciturn", definition: "Reserved in speech." },
  { word: "Anachronism", definition: "Something out of place in time." },
  { word: "Elegy", definition: "Mournful poem or piece." },
  { word: "Futile", definition: "Incapable of producing results." },
  { word: "Adroit", definition: "Skillful and clever, especially with hands or mind." },
  { word: "Ambivalent", definition: "Having mixed feelings about something." },
  { word: "Lassitude", definition: "Physical or mental weariness." },
  { word: "Hiatus", definition: "A pause or gap." },
  { word: "Foment", definition: "To instigate or stir up." },
  { word: "Impeccable", definition: "Faultless or perfect." },
  { word: "Emulate", definition: "To imitate to equal or surpass." },
  { word: "Precarious", definition: "Dangerously unstable." },
  { word: "Inert", definition: "Lacking ability to move." },
  { word: "Discrete", definition: "Separate and distinct." },
  { word: "Contentious", definition: "Causing disagreement or argument." },
  { word: "Burgeon", definition: "To grow or develop rapidly." },
  { word: "Coagulate", definition: "To thicken or congeal." },
  { word: "Apathy", definition: "Lack of interest, enthusiasm, or concern." },
  { word: "Propensity", definition: "Tendency to behave a certain way." },
  { word: "Dissonance", definition: "Lack of harmony." },
  { word: "Desultory", definition: "Lacking a clear plan or purpose." },
  { word: "Onerous", definition: "Involving heavy obligations." },
  { word: "Embellish", definition: "To decorate or add details." },
  { word: "Pervasive", definition: "Spreading widely." },
  { word: "Contrite", definition: "Feeling or expressing remorse." },
  { word: "Phlegmatic", definition: "Calm and unemotional." },
  { word: "Incorrigible", definition: "Not able to be corrected." },
  { word: "Mollify", definition: "To soothe anger or anxiety." },
  { word: "Bolster", definition: "To support or strengthen." },
  { word: "Volatile", definition: "Prone to rapid changes." },
  { word: "Chicanery", definition: "Deception or trickery." },
  { word: "Ostentation", definition: "Showy display to impress." },
  { word: "Partisan", definition: "Strong supporter of a cause." },
  { word: "Idiosyncrasy", definition: "Peculiar characteristic." },
  { word: "Gullible", definition: "Easily deceived." },
  { word: "Affable", definition: "Friendly, easy to talk to, and approachable." },
  { word: "Ascetic", definition: "Practicing severe self-discipline." },
  { word: "Conundrum", definition: "A confusing problem or question." },
  { word: "Acumen", definition: "Keen insight or quickness in understanding." },
  { word: "Fatuous", definition: "Silly or foolish." },
  { word: "Diffuse", definition: "Spread out over a large area." },
  { word: "Skeptic", definition: "Person who doubts accepted opinions." },
  { word: "Engender", definition: "To cause or give rise to." },
  { word: "Rescind", definition: "To revoke or cancel." },
  { word: "Erudite", definition: "Having great knowledge." },
  { word: "Ineffable", definition: "Too great to be expressed." },
  { word: "Strut", definition: "Proud walk." },
  { word: "Substantiate", definition: "To provide evidence for." },
  { word: "Connoisseur", definition: "An expert with refined taste." },
  { word: "Insipid", definition: "Lacking flavor or vigor." },
  { word: "Malleable", definition: "Easily shaped or influenced." },
  { word: "Discredit", definition: "To harm the reputation of." },
  { word: "Tenuous", definition: "Very weak or slight." },
  { word: "Rarefy", definition: "To make less dense." },
  { word: "Reprehensible", definition: "Deserving criticism." },
  { word: "Impetuous", definition: "Acting quickly without thought." },
  { word: "Buttress", definition: "To support or reinforce." },
  { word: "Deference", definition: "Respectful submission to authority." },
  { word: "Eclectic", definition: "Selecting from diverse sources." },
  { word: "Torpor", definition: "State of physical/mental inactivity." },
  { word: "Viable", definition: "Capable of working successfully." },
  { word: "Paragon", definition: "Perfect example of a quality." },
  { word: "Demur", definition: "To raise objections or show reluctance." },
  { word: "Opprobrium", definition: "Harsh criticism or disgrace." },
  { word: "Vitiate", definition: "To impair quality or effectiveness." },
  { word: "Alienate", definition: "To make someone feel isolated or estranged." },
  { word: "Hedonism", definition: "Pursuit of pleasure." },
  { word: "Subpoena", definition: "Writ commanding appearance in court." },
  { word: "Commensurate", definition: "Corresponding in size or degree." },
  { word: "Striated", definition: "Marked with stripes/grooves." },
  { word: "Euphemism", definition: "Mild expression for harsh reality." },
  { word: "Discerning", definition: "Having good judgment." },
  { word: "Irresolute", definition: "Uncertain or hesitant." },
  { word: "Fallacious", definition: "Based on mistaken belief." },
  { word: "Permeate", definition: "To spread throughout." },
  { word: "Proliferate", definition: "To increase rapidly." },
  { word: "Pathological", definition: "Compulsive or extreme." },
  { word: "Profound", definition: "Very deep or intense." },
  { word: "Zenith", definition: "Highest point or peak." },
  { word: "Mitigate", definition: "To make less severe." },
  { word: "Digression", definition: "A temporary departure from main subject." },
  { word: "Frugality", definition: "Economical use of resources." },
  { word: "Meticulous", definition: "Extremely careful and precise." },
  { word: "Supersede", definition: "To replace in authority." },
  { word: "Impugn", definition: "To challenge as false." },
  { word: "Obdurate", definition: "Stubbornly refusing to change." },
  { word: "Savor", definition: "To enjoy appreciatively." },
  { word: "Enigma", definition: "Mystery or puzzle." },
  { word: "Divest", definition: "To deprive or strip of." },
  { word: "Adulterate", definition: "To make impure by adding inferior substances." },
  { word: "Complacent", definition: "Self-satisfied and unaware of dangers." },
  { word: "Analogous", definition: "Comparable in certain respects." },
  { word: "Caustic", definition: "Capable of burning or corroding." },
  { word: "Oblique", definition: "Indirect or evasive." },
  { word: "Levity", definition: "Humor in serious situations." },
  { word: "Felicitous", definition: "Well-suited to the occasion." },
  { word: "Paucity", definition: "Scarcity or insufficiency." },
  { word: "Conflagration", definition: "A large destructive fire." },
  { word: "Repudiate", definition: "To reject as untrue." },
  { word: "Dearth", definition: "A scarcity or lack of something." },
  { word: "Recant", definition: "To withdraw a belief." },
  { word: "Transgression", definition: "Violation of law/rule." },
  { word: "Stigma", definition: "Mark of disgrace." },
  { word: "Neophyte", definition: "Beginner or novice." },
  { word: "Eloquent", definition: "Fluent and persuasive in speech." },
  { word: "Intractable", definition: "Hard to control or deal with." },
  { word: "Proclivity", definition: "Natural inclination." },
  { word: "Subside", definition: "To become less intense." },
  { word: "Advocate", definition: "To support or recommend publicly." },
  { word: "Gregarious", definition: "Sociable and outgoing." },
  { word: "Fervid", definition: "Intensely enthusiastic." },
  { word: "Truculent", definition: "Eager to argue." },
  { word: "Inured", definition: "Accustomed to difficulty." },
  { word: "Loquacious", definition: "Talkative." },
  { word: "Dupe", definition: "To deceive or trick." },
  { word: "Paradigm", definition: "Typical example or pattern." },
  { word: "Warranted", definition: "Justified or necessary." },
  { word: "Harangue", definition: "Loud, aggressive speech." },
  { word: "Abate", definition: "To reduce in intensity, amount, or severity." },
  { word: "Egregious", definition: "Shockingly bad or flagrant." },
  { word: "Malinger", definition: "To fake illness to avoid duty." },
  { word: "Benign", definition: "Gentle, kind, and harmless." },
  { word: "Refractory", definition: "Stubbornly resistant." },
  { word: "Dormant", definition: "Inactive or in a state of rest." },
  { word: "Empirical", definition: "Based on observation." },
  { word: "Daunt", definition: "To intimidate or cause fear." },
  { word: "Prevaricate", definition: "To avoid telling truth." },
  { word: "Invective", definition: "Abusive language." },
  { word: "Shard", definition: "Piece of broken glass/ceramic." },
  { word: "Banal", definition: "Lacking originality; boringly predictable." },
  { word: "Pristine", definition: "In original condition; unspoiled." },
  { word: "Aggrandize", definition: "To increase in power, status, or wealth." },
  { word: "Resolution", definition: "Firm decision to do something." },
  { word: "Endemic", definition: "Native to a particular area." },
  { word: "Specious", definition: "Misleadingly attractive." },
  { word: "Burnish", definition: "To polish or enhance." },
  { word: "Log", definition: "Record of events." },
  { word: "Dogmatic", definition: "Asserting opinions arrogantly." },
  { word: "Flout", definition: "To openly disregard rules." },
  { word: "Craven", definition: "Cowardly or lacking courage." },
  { word: "Obfuscate", definition: "To deliberately make unclear." },
  { word: "Morose", definition: "Sullen or gloomy." },
  { word: "Saturate", definition: "To soak thoroughly." },
  { word: "Disingenuous", definition: "Not candid; deceitful." },
  { word: "Impervious", definition: "Not allowing fluid to pass." },
  { word: "Precocious", definition: "Advanced for age." },
  { word: "Appease", definition: "To pacify by acceding to demands." },
  { word: "Imperative", definition: "Absolutely necessary." },
  { word: "Obsequious", definition: "Excessively obedient to please." },
  { word: "Supposition", definition: "Assumption without proof." },
  { word: "Secrete", definition: "To produce/release substance." },
  { word: "Fawn", definition: "To flatter excessively." },
  { word: "Antipathy", definition: "A strong feeling of dislike or aversion." },
  { word: "Relegate", definition: "To assign lower position." },
  { word: "Guile", definition: "Sly or cunning intelligence." },
  { word: "Facetious", definition: "Treating serious issues with humor." },
  { word: "Negligible", definition: "Too small to be considered." },
  { word: "Enigmatic", definition: "Difficult to interpret." },
  { word: "Abhor", definition: "To regard with disgust or hatred." },
  { word: "Archaic", definition: "Old-fashioned or outdated." },
  { word: "Arduous", definition: "Involving strenuous effort; difficult." },
  { word: "Dissemble", definition: "To conceal true motives." },
  { word: "Disseminate", definition: "To spread information widely." },
  { word: "Lucid", definition: "Clear and easy to understand." },
  { word: "Salubrious", definition: "Health-giving." },
  { word: "Amenable", definition: "Open to suggestion or willing to comply." },
  { word: "Boorish", definition: "Rough and bad-mannered." },
  { word: "Imperturbable", definition: "Unable to be upset." },
  { word: "Corroborate", definition: "To confirm with evidence." },
  { word: "Welter", definition: "Confused mass or mixture." },
  { word: "Distend", definition: "To expand or swell." },
  { word: "Catalyst", definition: "Something that causes change." },
  { word: "Castigate", definition: "To criticize or punish severely." },
  { word: "Implacable", definition: "Unable to be appeased." },
  { word: "Indolent", definition: "Lazy or avoiding activity." }
];
